//go:build relic

package bls

import (
	"bytes"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"errors"
	"strings"

	flowCrypto "github.com/onflow/flow-go/crypto"
)

// The SigningAlgorithm for BLS keys is BLSBLS12381 which is BLS on the BLS 12-381 curve.
// This is the only supported BLS signing algorithm in the flowCrypto package.
// BLS is used such that we can aggregate signatures into one signature.
const SigningAlgorithm = flowCrypto.BLSBLS12381

// The HashingAlgorithm for BLS keys is the following. This algorithm is used to hash input data onto the
// BLS 12-381 curve for generating signatures. The returned instance is a Hasher and can be used to
// generate BLS signatures with the Sign() method. This is the only supported BLS Hasher in the flowCrypto
// package. The input domainTag is a separation tag that defines the protocol and its subdomain. Such tag
// should be of the format: <protocol>-V<xx>-CS<yy>-with- where <protocol> is the name of the protocol,
// <xx> the protocol version number, and <yy> the index of the ciphersuite in the protocol.
var HashingAlgorithm = flowCrypto.NewExpandMsgXOFKMAC128("deso-V1-CS01-with-")

// AggregateSignatures takes in an input slice of bls.Signatures and aggregates them
// into a single bls.Signature. The assumption is that each of the input bls.Signatures
// were generated by different bls.PrivateKeys signing the same payload.
func AggregateSignatures(signatures []*Signature) (*Signature, error) {
	var flowSignatures []flowCrypto.Signature
	for _, signature := range signatures {
		flowSignatures = append(flowSignatures, signature.flowSignature)
	}
	aggregateFlowSignature, err := flowCrypto.AggregateBLSSignatures(flowSignatures)
	if err != nil {
		return nil, err
	}
	return &Signature{flowSignature: aggregateFlowSignature}, nil
}

// VerifyAggregateSignature takes in a slice of bls.PublicKeys, a bls.Signature, and a payload and returns
// true if every bls.PublicKey in the slice signed the payload. The input bls.Signature is the aggregate
// signature of each of their respective bls.Signatures for that payload.
func VerifyAggregateSignature(publicKeys []*PublicKey, signature *Signature, payloadBytes []byte) (bool, error) {
	var flowPublicKeys []flowCrypto.PublicKey
	for _, publicKey := range publicKeys {
		flowPublicKeys = append(flowPublicKeys, publicKey.flowPublicKey)
	}
	return flowCrypto.VerifyBLSSignatureOneMessage(flowPublicKeys, signature.flowSignature, payloadBytes, HashingAlgorithm)
}

//
// TYPES: PrivateKey
//

type PrivateKey struct {
	flowPrivateKey flowCrypto.PrivateKey
}

func NewPrivateKey() (*PrivateKey, error) {
	randomBytes := make([]byte, 64)
	_, err := rand.Read(randomBytes)
	if err != nil {
		return nil, err
	}
	flowPrivateKey, err := flowCrypto.GeneratePrivateKey(SigningAlgorithm, randomBytes)
	if err != nil {
		return nil, err
	}
	return &PrivateKey{flowPrivateKey: flowPrivateKey}, nil
}

func (privateKey *PrivateKey) Sign(payloadBytes []byte) (*Signature, error) {
	if privateKey == nil || privateKey.flowPrivateKey == nil {
		return nil, errors.New("PrivateKey is nil")
	}
	flowSignature, err := privateKey.flowPrivateKey.Sign(payloadBytes, HashingAlgorithm)
	if err != nil {
		return nil, err
	}
	return &Signature{flowSignature: flowSignature}, nil
}

func (privateKey *PrivateKey) PublicKey() *PublicKey {
	if privateKey == nil || privateKey.flowPrivateKey == nil {
		return nil
	}
	return &PublicKey{flowPublicKey: privateKey.flowPrivateKey.PublicKey()}
}

func (privateKey *PrivateKey) ToString() string {
	if privateKey == nil || privateKey.flowPrivateKey == nil {
		return ""
	}
	return privateKey.flowPrivateKey.String()
}

func (privateKey *PrivateKey) FromString(privateKeyString string) (*PrivateKey, error) {
	if privateKey == nil || privateKeyString == "" {
		return nil, nil
	}
	// Chop off leading 0x, if exists. Otherwise, does nothing.
	privateKeyStringCopy, _ := strings.CutPrefix(privateKeyString, "0x")
	// Convert from hex string to byte slice.
	privateKeyBytes, err := hex.DecodeString(privateKeyStringCopy)
	if err != nil {
		return nil, err
	}
	// Convert from byte slice to bls.PrivateKey.
	privateKey.flowPrivateKey, err = flowCrypto.DecodePrivateKey(SigningAlgorithm, privateKeyBytes)
	return privateKey, err
}

func (privateKey *PrivateKey) MarshalJSON() ([]byte, error) {
	// This is called automatically by the JSON library when converting a
	// bls.PrivateKey to JSON. This is currently not used, since the client
	// never shares their bls.PrivateKey over the network, but is included
	// here are as a nicety utility for completeness.
	return json.Marshal(privateKey.ToString())
}

func (privateKey *PrivateKey) UnmarshalJSON(data []byte) error {
	// This is called automatically by the JSON library when converting a
	// bls.PrivateKey from JSON. This is currently not used, since the client
	// never shares their bls.PrivateKey over the network, but is included
	// here are as a nicety utility for completeness.
	privateKeyString := ""
	err := json.Unmarshal(data, &privateKeyString)
	if err != nil {
		return err
	}
	_, err = privateKey.FromString(privateKeyString)
	return err
}

func (privateKey *PrivateKey) Eq(other *PrivateKey) bool {
	if privateKey == nil || privateKey.flowPrivateKey == nil || other == nil {
		return false
	}
	return privateKey.flowPrivateKey.Equals(other.flowPrivateKey)
}

//
// TYPES: PublicKey
//

type PublicKey struct {
	flowPublicKey flowCrypto.PublicKey
}

func (publicKey *PublicKey) Verify(signature *Signature, input []byte) (bool, error) {
	if publicKey == nil || publicKey.flowPublicKey == nil {
		return false, errors.New("bls.PublicKey is nil")
	}
	return publicKey.flowPublicKey.Verify(signature.flowSignature, input, HashingAlgorithm)
}

func (publicKey *PublicKey) ToBytes() []byte {
	var publicKeyBytes []byte
	if publicKey != nil && publicKey.flowPublicKey != nil {
		publicKeyBytes = publicKey.flowPublicKey.Encode()
	}
	return publicKeyBytes
}

func (publicKey *PublicKey) FromBytes(publicKeyBytes []byte) (*PublicKey, error) {
	if publicKey == nil || len(publicKeyBytes) == 0 {
		return nil, nil
	}
	var err error
	publicKey.flowPublicKey, err = flowCrypto.DecodePublicKey(SigningAlgorithm, publicKeyBytes)
	return publicKey, err
}

func (publicKey *PublicKey) ToString() string {
	if publicKey == nil || publicKey.flowPublicKey == nil {
		return ""
	}
	return publicKey.flowPublicKey.String()
}

func (publicKey *PublicKey) FromString(publicKeyString string) (*PublicKey, error) {
	if publicKey == nil || publicKeyString == "" {
		return nil, nil
	}
	// Chop off leading 0x, if exists. Otherwise, does nothing.
	publicKeyStringCopy, _ := strings.CutPrefix(publicKeyString, "0x")
	// Convert from hex string to byte slice.
	publicKeyBytes, err := hex.DecodeString(publicKeyStringCopy)
	if err != nil {
		return nil, err
	}
	// Convert from byte slice to bls.PublicKey.
	publicKey.flowPublicKey, err = flowCrypto.DecodePublicKey(SigningAlgorithm, publicKeyBytes)
	return publicKey, err
}

func (publicKey *PublicKey) MarshalJSON() ([]byte, error) {
	// This is called automatically by the JSON library when converting a
	// bls.PublicKey to JSON. This is useful when passing a bls.PublicKey
	// back and forth from the backend to the frontend as JSON.
	return json.Marshal(publicKey.ToString())
}

func (publicKey *PublicKey) UnmarshalJSON(data []byte) error {
	// This is called automatically by the JSON library when converting a
	// bls.PublicKey from JSON. This is useful when passing a bls.PublicKey
	// back and forth from the frontend to the backend as JSON.
	publicKeyString := ""
	err := json.Unmarshal(data, &publicKeyString)
	if err != nil {
		return err
	}
	_, err = publicKey.FromString(publicKeyString)
	return err
}

func (publicKey *PublicKey) Eq(other *PublicKey) bool {
	if publicKey == nil || publicKey.flowPublicKey == nil || other == nil {
		return false
	}
	return publicKey.flowPublicKey.Equals(other.flowPublicKey)
}

func (publicKey *PublicKey) Copy() *PublicKey {
	if publicKey == nil {
		return nil
	}
	return &PublicKey{
		flowPublicKey: publicKey.flowPublicKey,
	}
}

//
// TYPES: Signature
//

type Signature struct {
	flowSignature flowCrypto.Signature
}

func (signature *Signature) ToBytes() []byte {
	var signatureBytes []byte
	if signature != nil && signature.flowSignature != nil {
		signatureBytes = signature.flowSignature.Bytes()
	}
	return signatureBytes
}

func (signature *Signature) FromBytes(signatureBytes []byte) (*Signature, error) {
	if signature == nil || len(signatureBytes) == 0 {
		return nil, nil
	}
	signature.flowSignature = signatureBytes
	return signature, nil
}

func (signature *Signature) ToString() string {
	if signature == nil || signature.flowSignature == nil {
		return ""
	}
	return signature.flowSignature.String()
}

func (signature *Signature) FromString(signatureString string) (*Signature, error) {
	if signature == nil || signatureString == "" {
		return nil, nil
	}
	// Chop off leading 0x, if exists. Otherwise, does nothing.
	signatureStringCopy, _ := strings.CutPrefix(signatureString, "0x")
	// Convert from hex string to byte slice.
	signatureBytes, err := hex.DecodeString(signatureStringCopy)
	if err != nil {
		return nil, err
	}
	// Convert from byte slice to bls.Signature.
	signature.flowSignature = signatureBytes
	return signature, nil
}

func (signature *Signature) MarshalJSON() ([]byte, error) {
	// This is called automatically by the JSON library when converting a
	// bls.Signature to JSON. This is useful when passing a bls.Signature
	// back and forth from the backend to the frontend as JSON.
	return json.Marshal(signature.ToString())
}

func (signature *Signature) UnmarshalJSON(data []byte) error {
	// This is called automatically by the JSON library when converting a
	// bls.Signature from JSON. This is useful when passing a bls.Signature
	// back and forth from the frontend to the backend as JSON.
	signatureString := ""
	err := json.Unmarshal(data, &signatureString)
	if err != nil {
		return err
	}
	_, err = signature.FromString(signatureString)
	return err
}

func (signature *Signature) Eq(other *Signature) bool {
	if signature == nil || signature.flowSignature == nil || other == nil {
		return false
	}
	return bytes.Equal(signature.ToBytes(), other.ToBytes())
}

func (signature *Signature) Copy() *Signature {
	if signature == nil {
		return nil
	}
	if signature.flowSignature == nil {
		return &Signature{}
	}
	return &Signature{
		flowSignature: append([]byte{}, signature.flowSignature.Bytes()...),
	}
}
